var pre_words = ['The Return of', 'The Revenge of', 'Gaunt Grimdark Presents:'];

var case_words = ['Possession', 'Curse', 'Revenge', 'Terror', 'Haunting', 'Bane', 'Vexation', 'Unveiling', 'Ghost', 'Echoes', 'Sighs', 'Cry', 'Death', 'Tale', 'Account', 'Myth', 'Misery', 'Remains', 'Revivification', 'Mask', 'Hook', 'Drowning', 'Legend', 'Saga', 'Murder', 'Hand', 'Eyes', 'Vicegrip', 'Night', 'Burial', 'Nightmare', 'Dusk', 'Blood Moon', 'Trampling', 'Howl', 'Scream', 'Dawn', 'Grip', 'Clutches', 'Call', 'Torture', 'Souls', 'Wandering Spirits', 'Gaze', 'Crimes', 'Footsteps', 'Stain', 'Bite', 'Cloak', 'Veil', 'Hood', 'Stare', 'Corruption', 'Invitation', 'Last Ride', 'Rise', 'Path', 'Discovery', 'Trail', 'Anointing', 'Desecration', 'Oath', 'Scourge', 'Glint', 'Nails', 'Encounter', 'Betrayal', 'Emptiness', 'Feeding', 'Hunger'];
  
var adj_words = ['Haunted', 'Hidden', 'Bygone', 'Black', 'Blighted', 'Doomed', 'Lost', 'Unholy', 'Infernal', 'Abominable', 'Disgusting', 'Hapless', 'Undead', 'Heinous', 'Vile', 'Horrid', 'Noxious', 'Vicious', 'Repugnant', 'Abandoned', 'Evil', 'Dark', 'Wicked', 'Shrouded', 'Wretched', 'Wayward', 'Foul', 'Dreaded', 'Hulking', 'Wheezing', 'Conjoined', 'Amputated', 'Ghoulish', 'Rotted', 'Rotting', 'Decomposing', 'Crazed', 'Insane', 'Man-eating', 'Flesh-eating', 'Head-stomping', 'Soul-sucking', 'Stalking', 'Blood-curdling', 'Blood-soaked', 'Blood-drinking', 'Spine-tingling', 'Zombified', 'Contorted', 'Twisted', 'Woven', 'Writhing', 'Squirming', 'Imprisoned', 'Grief-stricken', 'Gothic', 'Soulless', 'Heartless', 'Eyeless', 'Mouthless', 'Many-legged', 'Sunken-eyed', 'Pox-ridden', 'Lonely', 'Decapitated', 'Headless', 'Bone-chilling', 'Whispering', 'Shrieking', 'Crumbling', 'Smoke-swirled', 'Unstoppable', 'Relentless', 'Lamp-lit', 'Ominous', 'Bed-ridden', 'Frozen', 'Unliving', 'Tempestuous', 'Bone-fingered', 'Poisonous', 'Faceless', 'Spider-stuffed', 'Boiled-alive', 'Unkillable', 'Barbed-wire', 'Unchained', 'Chained', 'Blood-drunk', 'Timeless', 'Shadow-wrapped', 'Wayfinding', 'Forlorn', 'Weeping'];

var noun_words = ['Monster', 'Creature', 'Thing', 'Entity', 'Monstrosity', 'Vampire', 'Ghost', 'Ghoul', 'Demon', 'Spirit', 'Corpse', 'Skull', 'Skeleton', 'Severed Head', 'Spiderling', 'Spider', 'Werewolf', 'Wolf', 'Doll', 'Mask', 'Hook', 'Zombie', 'Mummy', 'Witch', 'Statue', 'Clown', 'Child', 'Orphan', 'Twins', 'Triplets', 'Reflection', 'Leech', 'Thug', 'Painting', 'Menace', 'Murderer', 'Killer', 'Psycho', 'Fortune Teller', 'Witch Doctor', 'Portrait', 'Noose', 'Maw', 'Coffin', 'Grave', 'Photograph', 'Sawblade', 'Icepick', 'Pigknuckle', 'Sea Monster', 'Tentacle', 'Shadow', 'Trenchcoat', 'Crystal', 'Book', 'Journal', 'Necklace', 'Music Box', 'Mirror', 'Dollhouse', 'Creation', 'Gargoyle', 'Banshee', 'Gremlin', 'Specter', 'Phantom', 'Revenant', 'Wraith', 'Being', 'Goblet', 'Ivy', 'Snake', 'Serpent', 'Viper', 'Pumpkin', 'Gourd', 'Hayride', 'Haystack', 'Spinning Wheel', 'Goblin', 'Dirigible', 'Stallion', 'Wagon', 'Canoe'];

var in_place_words = ['House', 'Citadel', 'Mire', 'Manor', 'Chimney', 'Garden', 'Terrace', 'Greenhouse', 'Menagerie', 'Precipice', 'Grotto', 'Pit', 'Crags', 'Well', 'Swamp', 'Basement', 'Circus', 'Mausoleum', 'Crypt', 'Cove', 'Cave', 'Cemetary', 'Shack', 'Storeroom', 'Asylum', 'Chamber', 'Laboratory', 'Dungeon', 'Castle', 'Dollhouse', 'Stairway', 'Ballroom', 'Library', 'Cellar', 'Wine Cellar', 'Passageway', 'Stagecoach', 'Attic', 'Crawlspace', 'Dimension'];

var in_place_nothe = ['House', 'Manor', 'Cove', 'Tower', 'Cave', 'Asylum', 'Castle'];

var on_place_words = ['Hill', 'Lake', 'Swamp', 'Mountain', 'Island', 'Street', 'Docks', 'Harbor', 'Bluff', 'Cliff', 'Ridge', 'Peak'];

var end_words = ['Horror', 'Terror', 'Panic', 'Monstrosity', 'Encounter', 'Abomination', 'Hex', 'Vexation', 'Ghost', 'Contagion', 'Outbreak', 'Epidemic', 'Pandemic', 'Curse', 'Infestation', 'Affliction', 'Nightmare', 'Conjuring', 'Possession', 'Legend', 'Atrocity', 'Outrage', 'Barbarity', 'Saga', 'Frenzy', 'Murders', 'Burial', 'Eater', 'Crusher', 'Kidnappings', 'Stalker', 'Abductions', 'Accident', 'Hunter', 'Collector', 'Gatherer'];


